language: java
jdk: oraclejdk8

./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

install: true
script: ./mvnw clean install


cache:
  directories:
  - $HOME/.m2



script:
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)



